{
 "title": "star-wars-movies",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request count star-wars-movies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ktor_http_server_requests_seconds_count{address=\"127.0.0.1:8080\", instance=\"localhost:8080\", job=\"star-wars-movies\", method=\"GET\", route=~\".*(method:GET).\", status=\"200\", throwable=\"n/a\"}"
    }
   ]
  },
  {
   "title": "Request count star-wars-movies by id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ktor_http_server_requests_seconds_count{address=\"127.0.0.1:8080\", instance=\"localhost:8080\", job=\"star-wars-movies\", method=\"GET\", route=~\"/.*/{id}\", status=\"200\", throwable=\"n/a\"}"
    }
   ]
  },
  {
   "title": "Response time star-wars-movies ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ktor_http_server_requests_seconds{address=\"127.0.0.1:8080\", instance=\"localhost:8080\", job=\"star-wars-movies\", method=\"GET\", route=~\".*(method:GET).\", status=\"200\", throwable=\"n/a\"}"
    }
   ]
  },
  {
   "title": "Response time star-wars-movies by id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ktor_http_server_requests_seconds{address=\"127.0.0.1:8080\", instance=\"localhost:8080\", job=\"star-wars-movies\", method=\"GET\", route=~\"/.*/{id}\", status=\"200\", throwable=\"n/a\"}"
    }
   ]
  },
  {
   "title": "Simultaneous request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ktor_http_server_requests_active"
    }
   ]
  }
 ]
}