name: codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test-and-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
      - name: Before Install
        run: |
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar
      - name: Code coverage
        run: |
          ./gradlew detektGenerateConfig
          ./gradlew build
          ./gradlew test
          ./gradlew jacocoTestReport
          ./gradlew jacocoTestCoverageVerification
          ./gradlew jacocoMergeReport
          bash <(curl -s https://codecov.io/bash)